version: "3.7"
networks:
  followerInstagram:
services:
  nginx:
    image: nginx:latest
    container_name: nginx-${APP_NAME}
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - followerInstagram
  mysql:
    image: mysql:latest
    container_name: mysql-${APP_NAME}
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234I
      - MYSQL_DATABASE=follower_instagram
    depends_on:
      - php
    networks:
      - followerInstagram
  redis:
    image: redis:latest
    container_name: redis-interview
    ports:
      -  "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/data/redis:/data
    networks:
      - followerInstagram
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-${APP_NAME}
    volumes:
      -  "./:/var/www/html"
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
    networks:
      - followerInstagram
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    restart: always
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: root
    depends_on:
     - mysql
     - php
    ports:
     - "8080:80"
    networks:
     - followerInstagram
